### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by gpldecha** [epfl-lasa/fri-library-ros#1]
This repo should be public.

**Comment by sinamr88** [comment]
As far as I know, KUKA-FRI is not a open source library and we bought it from KUKA. Just make sure that you don't make this library public.

**Comment by gpldecha** [comment]
It is open source, make it public.

**Comment by felixduvallet** [comment]
The code seems to be mostly from [Stanford's group](http://cs.stanford.edu/people/tkr/fri/html/index.html), but there is also a .so file. Where does the lib come from: is it generated from the code or did we get it elsewhere?

**Comment by nisommer** [comment]
I'm pretty sure the .so file is from kuka.

Le mer. 20 janv. 2016 11:45, Felix Duvallet notifications@github.com a
écrit :

**Comment by KlasKronander** [comment]
What do anyone benefit from making this public? It is only a ros-packaged version of Torsten Kroeger's FRI-wrapper (stanford). I am not sure if the kuka fri components (which are also part of this repo!) are open source or not. I suggest we keep it private to be on the safe side. This library is already available to the public anyway via Stanford.

**Comment by felixduvallet** [comment]
I have not found any usage of either `libFRILibrary_ros.so` or `libfri_library_ros.so` anywhere. This package builds without them, and the lib files are not installed anywhere.
Can someone point to a package that requires either lib file?

**Comment by nisommer** [comment]
The library is loaded at runtime by lwrmain

Le mer. 20 janv. 2016 13:19, Felix Duvallet notifications@github.com a
écrit :

**Comment by nisommer** [comment]
ok let met have another look at the code to check.

**Comment by nisommer** [comment]
Ok, they don't seem to be used anywhere.
